# Generated by Django 4.2.7 on 2026-01-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0011_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNATest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('test_date', models.DateField()),
                ('result_date', models.DateField()),
                ('CXCL13', models.FloatField(blank=True, null=True)),
                ('CD8A', models.FloatField(blank=True, null=True)),
                ('CCR7', models.FloatField(blank=True, null=True)),
                ('C1QA', models.FloatField(blank=True, null=True)),
                ('LY9', models.FloatField(blank=True, null=True)),
                ('CXCL10', models.FloatField(blank=True, null=True)),
                ('CXCL9', models.FloatField(blank=True, null=True)),
                ('STAT1', models.FloatField(blank=True, null=True)),
                ('CCND1', models.FloatField(blank=True, null=True)),
                ('MKI67', models.FloatField(blank=True, null=True)),
                ('TOP2A', models.FloatField(blank=True, null=True)),
                ('BRCA1', models.FloatField(blank=True, null=True)),
                ('RAD51', models.FloatField(blank=True, null=True)),
                ('PRKDC', models.FloatField(blank=True, null=True)),
                ('POLD3', models.FloatField(blank=True, null=True)),
                ('POLB', models.FloatField(blank=True, null=True)),
                ('LIG1', models.FloatField(blank=True, null=True)),
                ('ERBB2', models.FloatField(blank=True, null=True)),
                ('ESR1', models.FloatField(blank=True, null=True)),
                ('PGR', models.FloatField(blank=True, null=True)),
                ('ARAF', models.FloatField(blank=True, null=True)),
                ('PIK3CA', models.FloatField(blank=True, null=True)),
                ('AKT1', models.FloatField(blank=True, null=True)),
                ('MTOR', models.FloatField(blank=True, null=True)),
                ('TP53', models.FloatField(blank=True, null=True)),
                ('PTEN', models.FloatField(blank=True, null=True)),
                ('MYC', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rna_tests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'RNA Test',
                'verbose_name_plural': 'RNA Tests',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('test_date', models.DateField()),
                ('result_date', models.DateField()),
                ('wbc', models.FloatField(blank=True, null=True, verbose_name='WBC')),
                ('wbc_unit', models.CharField(default='x10^9/L', max_length=20)),
                ('hemoglobin', models.FloatField(blank=True, null=True, verbose_name='Hemoglobin')),
                ('hemoglobin_unit', models.CharField(default='g/dL', max_length=20)),
                ('neutrophils', models.FloatField(blank=True, null=True, verbose_name='Neutrophils')),
                ('neutrophils_unit', models.CharField(default='x10^9/L', max_length=20)),
                ('lymphocytes', models.FloatField(blank=True, null=True, verbose_name='Lymphocytes')),
                ('lymphocytes_unit', models.CharField(default='x10^9/L', max_length=20)),
                ('platelets', models.FloatField(blank=True, null=True, verbose_name='Platelets')),
                ('platelets_unit', models.CharField(default='x10^9/L', max_length=20)),
                ('nlr', models.FloatField(blank=True, null=True, verbose_name='NLR')),
                ('crp', models.FloatField(blank=True, null=True, verbose_name='CRP')),
                ('crp_unit', models.CharField(default='mg/L', max_length=20)),
                ('ldh', models.FloatField(blank=True, null=True, verbose_name='LDH')),
                ('ldh_unit', models.CharField(default='U/L', max_length=20)),
                ('albumin', models.FloatField(blank=True, null=True, verbose_name='Albumin')),
                ('albumin_unit', models.CharField(default='g/dL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
    ]
