# Generated by Django 4.2.27 on 2026-01-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="case_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="channel_kind",
            field=models.CharField(
                blank=True,
                choices=[("dept", "Department"), ("shift", "Shift")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="dept_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[("case", "Case"), ("channel", "Channel")],
                default="case",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="shift_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="ShiftMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_code", models.CharField(max_length=64)),
                ("shift_code", models.CharField(max_length=64)),
                ("role", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dept_code", "shift_code")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_code", models.CharField(max_length=64)),
                ("role", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dept_code")},
            },
        ),
    ]
