# Generated by Django 4.2.27 on 2026-01-14 00:59

from django.db import migrations, models
from django.db.models import Max


def backfill_last_message_at(apps, schema_editor):
    ChatRoom = apps.get_model("chat", "ChatRoom")
    Message = apps.get_model("chat", "Message")

    last_seen = (
        Message.objects.values("room_id")
        .annotate(last_timestamp=Max("timestamp"))
        .iterator()
    )
    for row in last_seen:
        ChatRoom.objects.filter(id=row["room_id"]).update(
            last_message_at=row["last_timestamp"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatroomuserstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_message_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="chatroomuserstate",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_last_message_at, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "case_key"], name="chat_chatro_room_ty_d847f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "channel_kind", "dept_code", "shift_code"],
                name="chat_chatro_room_ty_ea3116_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroomuserstate",
            index=models.Index(
                fields=["user", "room"], name="chat_chatro_user_id_c99f33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroomuserstate",
            index=models.Index(
                fields=["user", "is_hidden"], name="chat_chatro_user_id_f1f7bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "id"], name="chat_messag_room_id_12c833_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "timestamp"], name="chat_messag_room_id_645da7_idx"
            ),
        ),
    ]
