# Generated by Django 4.2.27 on 2026-01-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_attachment_message_attachment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroomuserstate",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
