# Generated by Django 4.2.27 on 2026-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[("case", "Case"), ("channel", "Channel"), ("group", "Group")],
                default="case",
                max_length=20,
            ),
        ),
    ]
