# Generated by Django 4.2.27 on 2026-02-02 00:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceOfCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("phone", models.CharField(max_length=50, verbose_name="연락처")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("self", "본인"),
                            ("family", "가족"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="환자와의 관계",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("compliment", "칭찬"),
                            ("complaint", "불만"),
                            ("suggestion", "제안 및 건의"),
                        ],
                        max_length=20,
                        verbose_name="상담 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="접수일"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="처리 완료 여부"),
                ),
            ],
            options={
                "verbose_name": "고객의 소리",
                "verbose_name_plural": "고객의 소리(VOC) 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
