# Generated by Django 4.2.27 on 2026-02-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_voiceofcustomer"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="voiceofcustomer",
            table="voice_of_customer",
        ),
    ]
