# Generated by Django 4.2.7 on 2026-01-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocs', '0003_order_type_tissue_exam'),
    ]

    operations = [
        # LabTestResult는 이미 존재하므로 Django 상태만 업데이트 (데이터베이스 작업 없음)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='LabTestResult',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('test_results', models.JSONField(default=dict, verbose_name='검사 결과 데이터')),
                        ('ai_findings', models.TextField(blank=True, verbose_name='AI 소견')),
                        ('ai_confidence_score', models.FloatField(blank=True, null=True, verbose_name='AI 신뢰도')),
                        ('ai_report_image', models.TextField(blank=True, verbose_name='AI 임상 리포트 이미지 (base64)')),
                        ('ai_prediction', models.CharField(blank=True, max_length=50, verbose_name='AI 예측 결과')),
                        ('notes', models.TextField(blank=True, verbose_name='추가 메모')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='입력일')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                        ('input_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_results', to=settings.AUTH_USER_MODEL, verbose_name='결과 입력자')),
                        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_result', to='ocs.order', verbose_name='주문')),
                    ],
                    options={
                        'verbose_name': '검사 결과',
                        'verbose_name_plural': '검사 결과들',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        # PathologyAnalysisResult도 이미 존재하므로 Django 상태만 업데이트 (데이터베이스 작업 없음)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PathologyAnalysisResult',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('class_id', models.IntegerField(verbose_name='클래스 ID')),
                        ('class_name', models.CharField(max_length=50, verbose_name='클래스 이름')),
                        ('confidence', models.FloatField(verbose_name='신뢰도')),
                        ('probabilities', models.JSONField(default=dict, verbose_name='클래스별 확률')),
                        ('filename', models.CharField(max_length=500, verbose_name='파일명')),
                        ('image_url', models.TextField(blank=True, verbose_name='이미지 URL')),
                        ('findings', models.TextField(blank=True, verbose_name='소견')),
                        ('recommendations', models.TextField(blank=True, verbose_name='권고사항')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석일')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                        ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_analyses', to=settings.AUTH_USER_MODEL, verbose_name='분석자')),
                        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_analysis', to='ocs.order', verbose_name='주문')),
                    ],
                    options={
                        'verbose_name': '병리 분석 결과',
                        'verbose_name_plural': '병리 분석 결과들',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
    ]
