# Generated by Django 4.2.7 on 2026-01-25 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0004_labtestresult_pathologyanalysisresult_and_more'),
    ]

    operations = [
        # 인덱스 이름 변경은 실제 데이터베이스에 이미 존재할 수 있으므로 스킵
        # Django 상태만 업데이트 (실제 데이터베이스 작업 없음)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='ocs_notific_user_id_916063_idx',
                    old_name='ocs_notific_user_id_idx',
                ),
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='ocs_notific_user_id_5f6483_idx',
                    old_name='ocs_notific_user_cr_idx',
                ),
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='ocs_notific_notific_c3a3d9_idx',
                    old_name='ocs_notific_type_idx',
                ),
                migrations.RenameIndex(
                    model_name='order',
                    new_name='ocs_order_patient_4124cc_idx',
                    old_name='ocs_order_patient_idx',
                ),
                migrations.RenameIndex(
                    model_name='order',
                    new_name='ocs_order_doctor__cd300e_idx',
                    old_name='ocs_order_doctor_idx',
                ),
                migrations.RenameIndex(
                    model_name='order',
                    new_name='ocs_order_target__efe302_idx',
                    old_name='ocs_order_target_idx',
                ),
                migrations.RenameIndex(
                    model_name='order',
                    new_name='ocs_order_priorit_0fa20a_idx',
                    old_name='ocs_order_priority_idx',
                ),
            ],
            database_operations=[],
        ),
        # 필드 타입 변경은 실제 데이터베이스 작업 필요
        migrations.AlterField(
            model_name='allergycheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='druginteractioncheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imaginganalysisresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
