# Generated by Django 4.2.7 on 2026-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs', '0005_add_order_id_to_pathology'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologyanalysisresult',
            name='dzi_url',
            field=models.TextField(blank=True, verbose_name='DZI 메타데이터 URL'),
        ),
        migrations.AddField(
            model_name='pathologyanalysisresult',
            name='viewer_url',
            field=models.TextField(blank=True, verbose_name='뷰어 URL'),
        ),
    ]
